name: Release Ruby Gem

on:
  push:
    tags:
      - "v*.*.*" # Trigger the workflow for version tags like v1.2.3
  workflow_dispatch:
jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.3.6
   
    - name: Check the code
      run: bundle update 
      run: rake test 
      run: rake install 
      run: rake rubocop 
    
    - name: Release
      run: rake publish

    - name: Create GitHub Release
      uses: actions/create-release@v1
      with:
        tag_name: ${{ github.ref_name }} # Use the tag name triggering the workflow
        release_name: ${{ github.ref_name }} # Use the same name for the release
        body: |
            You can find all the information about the gem right here:
            https://rubygems.org/gems/newsman
            If you have any questions, just send them to:
            https://github.com/volodya-lombrozo/newsman
        draft: false
        prerelease: false

