---
name: newsman-status
on:
  schedule:
    - cron: "0 6 * * 1"
  push:
    branches:
      - main 
  workflow_dispatch:
concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true
permissions:
  contents: write
jobs:
  newsman-daily-status:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2
      - run: gem install newsman 
      - name: Run newsman script
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_GITHUB_TOKEN }}
          OPENAI_TOKEN: ${{ secrets.OPENAI_TOKEN }}
        run: newsman --name "Vladimir Zakharov" --username "volodya-lombrozo" --repository objectionary/jeo-maven-plugin,objectionary/opeo-maven-plugin -o html -t Objectionary 
      - run: mkdir -p gh-pages/$(date +'%Y/%m/%d')
      - run: cp *.html gh-pages/$(date +'%Y/%m/%d')
      - uses: JamesIves/github-pages-deploy-action@v4.6.1
        with:
          branch: gh-pages
          folder: gh-pages
          clean: false
