---
name: newsman-status
on:
  schedule:
    - cron: "0 4 * * 1"
  workflow_dispatch:
concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true
permissions:
  contents: write
jobs:
  newsman-daily-status:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2
      - run: gem install newsman 
      - name: Run newsman script with gpt-4o
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_GITHUB_TOKEN }}
          OPENAI_TOKEN: ${{ secrets.OPENAI_TOKEN }}
        run: newsman --name "Vladimir Lombrozo" --username "volodya-lombrozo" --model gpt-4o --repository objectionary/jeo-maven-plugin,objectionary/opeo-maven-plugin,objectionary/eo,objectionary/lints,volodya-lombrozo/jsmith,cqfn/refrax -o html -t Objectionary
      - run: mkdir -p gh-pages/$(date +'%Y/%m/%d')
      - run: cp *.html gh-pages/$(date +'%Y/%m/%d')
      - uses: JamesIves/github-pages-deploy-action@v4.7.3
        with:
          branch: gh-pages
          folder: gh-pages
          clean: false
